# Generated by Django 5.2 on 2025-08-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('baja', 'Baja')], default='activo', max_length=20)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_api.empleado')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('responsabilidades', models.TextField(blank=True, null=True)),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='rest_api.departamento')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.RESTRICT, to='rest_api.rol'),
        ),
    ]
