# Generated by Django 5.2 on 2025-08-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edad',
            field=models.IntegerField(default=18),
        ),
    ]
