services:
  backend:
    build: ./backend_api_django/gestor_DISI
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend_api_django/gestor_DISI/.env.pro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend_api_django/gestor_DISI/.env.pro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"   # solo accesible internamente
    depends_on:
      - backend
#    environment:
#      - API_URL=http://<IP_PUBLICA>:8000 

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"  # el usuario accede solo por este puerto
    volumes:
      - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
