services:
  backend:
    build: ./backend_api_django/gestor_DISI   
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend_api_django/gestor_DISI/.env.pro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - ./backend_api_django/gestor_DISI/.env.pro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"   
    depends_on:
      - backend
#    environment:
#      - VITE_API_URL=http://backend:8000 

volumes:
  postgres_data:
